### ISSUE TITLE
An issue

### ISSUE THREAD

**Issue by thisvijay** [rajeshkumarlingavel/RichEditorView#1]
this is issue description

**Comment by rajeshkumar-l-2098** [comment]
Hi possssssBonnie RunolfssonManagerSales & Marketing@Surface Sureve---- On&nbsp;Tue, 4 Dec 2018 12:57:14 +0530&nbsp;&nbsp; wrote ---- this is issue description

**Comment by thisvijay** [comment]
ok to resolve
